/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.funecirce.circlesexpanding;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class Main extends JFrame{



    public static void initWindow() {
            Main f = new Main();
            f.setTitle("Circles Expanding");
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            Board board = new Board();
            f.add(board);
            f.addMouseListener(board);
            f.setResizable(true);
    
            f.pack();
    
            f.setVisible(true);
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> { initWindow(); });
    }
}
